spring.application.name=publication-service
server.port=8081

spring.datasource.url=jdbc:mariadb://nc-country.mysql.database.azure.com:3306/nc_pet
spring.datasource.password=1P3aYV2WDZlcNh1


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect