server:
  port: 443

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes: #Agregar sus rutas de la forma en la que esta abajo
#        - id: clientes-service
#          uri: lb://CLIENTES-SERVICE
#          predicates:
#            - Path=/clientes/**
#          filters:
#            - AuthFilter
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**